version: "3.7"

services:
  ahbicht-backend:
    image: ghcr.io/hochfrequenz/ahbicht-functions:v1.1.0
    environment:
      - StorageProvider=Directory
    ports:
      - ${AHBICHT_FUNCTIONS_REST_PORT:-7071}:7071
