version: "3.7"

services:
  transformer:
    image: ghcr.io/hochfrequenz/ahbicht-functions:v0.4.1
    environment:
      - StorageProvider=Directory
    ports:
      - ${AHBICHT_FUNCTIONS_REST_PORT:-7071}:7071
