name: Nuget Release

on:
  release:
    types: [created, edited]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9
      - name: Log into registry
        # GHCR_PAT is a personal access token for the Github Container Registry; You can create it using the following steps:
        # 1) Go to https://github.com/settings/tokens
        # 2) Create a new token (classic as of 2024-01-31)
        # 3) Select the following scopes: read:packages
        # GHCR_USR is the username for the Github Container Registry; it has to match the PAT and is the username of the Github account that created the PAT
        # You can update the tokens in the repository settings:
        # https://github.com/Hochfrequenz/AhbichtClient/settings/secrets/actions/GHCR_PAT
        # https://github.com/Hochfrequenz/AhbichtClient/settings/secrets/actions/GHCR_USR
        # Tokens will expire 2025-07-01
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ secrets.GHCR_USR }} --password-stdin
      - name: Start containers
        run: docker compose -f "AhbichtClient/AhbichtClient.IntegrationTest/docker-compose.yml" up -d
      - name: Build/Check for compile errors (dotnet build)
        working-directory: "AhbichtClient"
        run: dotnet build --configuration Release
      - name: Run Unit Tests (dotnet test) # never ever release with failing tests!
        working-directory: "AhbichtClient"
        run: dotnet test --configuration Release
  push_release:
    needs: run_tests
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9
      - uses: olegtarasov/get-tag@v2.1
        id: tagTBC
        with:
          tagRegex: "v(\\d+\\.\\d+\\.\\d+)"
      - name: Build/Check for compile errors (dotnet build)
        working-directory: "AhbichtClient"
        run: dotnet build --configuration Release
      - name: Create Package AhbichtClient (dotnet pack)
        working-directory: "AhbichtClient/AhbichtClient"
        run: dotnet pack AhbichtClient.csproj --configuration Release -p:PackageVersion="${{ steps.tagTBC.outputs.tag }}"
      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1
      - name: Nuget push AhbichtClient
        working-directory: "AhbichtClient/AhbichtClient"
        # token: https://github.com/Hochfrequenz/AhbichtClient.net/settings/secrets/actions/NUGET_ORG_PUSH_TOKEN
        # expires 2025-07-17; token is owned by konstantin as of now.
        run: |
          nuget setApiKey ${{ secrets.NUGET_ORG_PUSH_TOKEN }}
          nuget push .\bin\Release\*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -NoSymbols
